#!/usr/bin/env sh
# Tests for the pre-build PM check: the three hooks, and the settings.json pass
# inside install.sh.
#
# Every payload here is copied from the shapes documented at
# https://code.claude.com/docs/en/hooks.md — `prompt` on UserPromptSubmit,
# `source` on SessionStart, `agent_id` only inside a subagent. That is the whole
# point of this file: an earlier round of tests passed against an invented field
# name and certified a hook that could never fire.
#
# Lives under .github/ so `install.sh` does not ship it to operators — its copy
# loop takes every non-dot top-level directory.
#
# Run: sh .github/tests/pm-check-hooks.sh
#
# SC2319: `check` is always called on the line after the condition it reports on,
# which is exactly the pattern the warning guards against getting wrong.
# SC1007: `CDPATH= cd` is a deliberate one-command environment override.
# SC1090: the sourced env file is generated by the hook under test at runtime.
# SC2016: the prune fixtures pass shell snippets to `eval`, so deferring
#         expansion until the fixture's own `$cfg` exists is the point.
# shellcheck disable=SC2319,SC1007,SC1090,SC2016

set -u

repo=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
detect="$repo/hooks/pm-check-detect.sh"
gate="$repo/hooks/pm-check-gate.sh"
reset="$repo/hooks/pm-check-reset.sh"
done_script="$repo/hooks/pm-check-done.sh"

work=$(mktemp -d) || exit 1
trap 'rm -rf "$work"' EXIT INT TERM

passed=0
failed=0

ok() {
  passed=$((passed + 1))
  printf '  ok   %s\n' "$1"
}

fail() {
  failed=$((failed + 1))
  printf '  FAIL %s\n' "$1"
  [ $# -lt 2 ] || printf '       %s\n' "$2"
}

check() { # description, condition-already-evaluated via $?
  if [ "$2" = "0" ]; then ok "$1"; else fail "$1" "${3:-}"; fi
}

# A clean per-case state dir, so no case can pass on another's leftovers.
fresh() {
  state="$work/state.$$.$1"
  rm -rf "$state"
  mkdir -p "$state"
  claude_home="$work/home.$$.$1"
  rm -rf "$claude_home"
  mkdir -p "$claude_home"
}

run_hook() { # script, payload  → stdout; state via $state, config via $claude_home
  printf '%s' "$2" | env \
    TMPDIR="$state" \
    CLAUDE_CONFIG_DIR="$claude_home" \
    CLAUDE_PM_CHECK="${CLAUDE_PM_CHECK:-}" \
    CLAUDE_ENV_FILE="${CLAUDE_ENV_FILE:-}" \
    sh "$1" 2>/dev/null
}

SID=abc123
pending_for() { printf '%s/claude-pm-check-%s.pending' "$state" "$1"; }
done_for() { printf '%s/claude-pm-check-%s.done' "$state" "$1"; }

# Verbatim shapes from the hooks reference.
prompt_payload() {
  printf '{"session_id":"%s","transcript_path":"/tmp/t.jsonl","cwd":"/tmp","permission_mode":"default","hook_event_name":"UserPromptSubmit","prompt":"%s"}' \
    "$SID" "$1"
}
pretool_payload() {
  printf '{"session_id":"%s","prompt_id":"550e8400","transcript_path":"/tmp/t.jsonl","cwd":"/tmp","permission_mode":"default","hook_event_name":"PreToolUse","tool_name":"Write","tool_input":{"file_path":"/tmp/x.py","content":"x"},"tool_use_id":"toolu_01"%s}' \
    "$SID" "$1"
}
sessionstart_payload() {
  printf '{"session_id":"%s","transcript_path":"/tmp/t.jsonl","cwd":"/tmp","hook_event_name":"SessionStart","source":"%s","model":"claude-sonnet-5"}' \
    "$SID" "$1"
}

echo "pm-check-detect.sh"

fresh d1
out=$(run_hook "$detect" "$(prompt_payload "build me a dashboard for shift fill rates")")
[ -f "$(pending_for $SID)" ]
check "build-shaped prompt marks the session pending" $?
case "$out" in *'"additionalContext"'*) r=0 ;; *) r=1 ;; esac
check "build-shaped prompt injects additionalContext" $r "got: $out"
case "$out" in *"$(done_for $SID)"*) r=0 ;; *) r=1 ;; esac
check "injected context carries the absolute completion path" $r "got: $out"

# Regression guard for the bug this whole round exists to fix. The field is
# `prompt`; a hook reading `prompt_text` gets nothing and the gate never arms.
fresh d2
run_hook "$detect" "$(printf '{"session_id":"%s","hook_event_name":"UserPromptSubmit","prompt_text":"build me a dashboard"}' "$SID")" >/dev/null
[ ! -f "$(pending_for $SID)" ]
check "a payload carrying only prompt_text does NOT arm the gate" $?

fresh d3
run_hook "$detect" "$(prompt_payload "what does the shift fill rate look like this week")" >/dev/null
[ ! -f "$(pending_for $SID)" ]
check "a question does not arm the gate" $?

fresh d4
run_hook "$detect" "$(prompt_payload "add a comment explaining this")" >/dev/null
[ ! -f "$(pending_for $SID)" ]
check "verb without an artifact noun does not arm the gate" $?

fresh d5
run_hook "$detect" "$(prompt_payload "the daily dashboard is broken")" >/dev/null
[ ! -f "$(pending_for $SID)" ]
check "noun without an intent verb does not arm the gate" $?

for edit_case in "rebuild the report" "readd the endpoint" "unmake the pipeline"; do
  fresh "d6$(echo "$edit_case" | tr -d ' ')"
  run_hook "$detect" "$(prompt_payload "$edit_case")" >/dev/null
  [ ! -f "$(pending_for $SID)" ]
  check "word boundary: \"$edit_case\" does not arm the gate" $?
done

fresh d7
run_hook "$detect" "$(prompt_payload "set up a cron job for the recap")" >/dev/null
[ -f "$(pending_for $SID)" ]
check "multi-word verb \"set up\" still arms the gate" $?

# Gerunds. A bare \bbuild\b cannot match "building", and these are plausibly the
# most common phrasing of a build request.
i=0
for gerund in \
  "building an internal tool for recruiting" \
  "creating a dashboard for shift fill" \
  "spinning up a new service for the roster" \
  "standing up a slack bot for daily recaps" \
  "scaffolding a new integration with paylocity"
do
  i=$((i + 1))
  fresh "d11$i"
  run_hook "$detect" "$(prompt_payload "$gerund")" >/dev/null
  [ -f "$(pending_for $SID)" ]
  check "gerund arms the gate: \"$gerund\"" $?
done

# Edit and bug-fix requests. SKILL.md says explicitly this is not a pre-edit
# check; each of these gated before the indefinite-determiner rule.
i=0
for edit_case in \
  "make sure the pipeline job passes ci" \
  "add a comment to the script explaining the cron" \
  "the report page is broken, can you add logging to the job" \
  "add a test to the job runner" \
  "fix the dashboard so the report page loads"
do
  i=$((i + 1))
  fresh "d12$i"
  run_hook "$detect" "$(prompt_payload "$edit_case")" >/dev/null
  [ ! -f "$(pending_for $SID)" ]
  check "edit request does NOT arm the gate: \"$edit_case\"" $?
done

# A quoted phrase arrives with escaped quotes. Requiring a closing quote
# truncated the prompt at the first one, dropping the noun and skipping the
# check entirely.
fresh d13
run_hook "$detect" "$(printf '{"session_id":"%s","hook_event_name":"UserPromptSubmit","prompt":"build a \\"shift fill\\" dashboard for ops"}' "$SID")" >/dev/null
[ -f "$(pending_for $SID)" ]
check "a quoted phrase in the prompt still arms the gate" $?

# A prompt far larger than the byte cap. Guards the pairing that makes the cap
# safe: extraction must not require a closing quote, or capping turns every long
# prompt into a silent bypass.
fresh d14
big=$(printf 'build me a dashboard for shift fill rates. context: '; head -c 400000 /dev/zero | tr '\0' 'x')
run_hook "$detect" "$(prompt_payload "$big")" >/dev/null
[ -f "$(pending_for $SID)" ]
check "a 400KB prompt still arms the gate" $?

fresh d8
: > "$claude_home/.pm-check-off"
run_hook "$detect" "$(prompt_payload "build me a dashboard")" >/dev/null
[ ! -f "$(pending_for $SID)" ]
check "the .pm-check-off flag disables the detector" $?

fresh d9
out=$(CLAUDE_PM_CHECK=off run_hook "$detect" "$(prompt_payload "build me a dashboard")")
[ ! -f "$(pending_for $SID)" ]
check "CLAUDE_PM_CHECK=off disables the detector" $?

fresh d10
: > "$(done_for $SID)"
run_hook "$detect" "$(prompt_payload "build me a dashboard")" >/dev/null
[ ! -f "$(pending_for $SID)" ]
check "a session that already ran the check is not re-armed" $?

echo "pm-check-gate.sh"

fresh g1
: > "$(pending_for $SID)"
out=$(run_hook "$gate" "$(pretool_payload "")")
case "$out" in *'"permissionDecision":"deny"'*) r=0 ;; *) r=1 ;; esac
check "a pending session denies Write" $r "got: $out"
case "$out" in *"$(done_for $SID)"*) r=0 ;; *) r=1 ;; esac
check "the deny message carries the absolute completion path" $r "got: $out"

fresh g2
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -z "$out" ]
check "a session that never asked to build is not gated" $?

fresh g3
: > "$(pending_for $SID)"
: > "$(done_for $SID)"
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -z "$out" ]
check "a completed check lifts the gate" $?

# `agent_id` is present only inside a subagent call, and `session_id` stays the
# parent's — so this payload is a subagent writing under a gated parent.
fresh g4
: > "$(pending_for $SID)"
out=$(run_hook "$gate" "$(pretool_payload ',"agent_id":"agent-abc123","agent_type":"Explore"')")
[ -z "$out" ]
check "a subagent Write under a gated parent is allowed" $?

fresh g5
: > "$(pending_for $SID)"
: > "$claude_home/.pm-check-off"
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -z "$out" ]
check "the .pm-check-off flag lifts the gate mid-session" $?

# A PreToolUse payload embeds the file being written, so an unbounded scan makes
# every Write in every session pay for the file's size — org-wide, on writes
# that are never gated.
#
# Asserted without a stopwatch. The extractor is greedy, so it returns the LAST
# match: a decoy session_id parked beyond the byte cap is invisible to a bounded
# scan and wins an unbounded one. Denying here therefore proves the cap is in
# force, deterministically and without a timing threshold that would go flaky on
# a loaded CI box.
fresh g6
blob=$(head -c 2000000 /dev/zero | tr '\0' 'x')
big_payload=$(printf '{"session_id":"%s","hook_event_name":"PreToolUse","tool_name":"Write","tool_input":{"file_path":"/tmp/x","content":"%s"},"session_id":"decoy-past-the-cap"}' "$SID" "$blob")
: > "$(pending_for $SID)"
out=$(run_hook "$gate" "$big_payload")
case "$out" in *'"deny"'*) r=0 ;; *) r=1 ;; esac
check "the session_id scan stops at the byte cap on a 2MB payload" $r

fresh g7
out=$(run_hook "$gate" "$big_payload")
[ -z "$out" ]
check "a 2MB Write in an ungated session is still allowed" $?

# A control character in TMPDIR must not produce invalid JSON: Claude Code
# discards a malformed hook output whole, turning this deny into an allow.
fresh g8
state="$work/tab	dir.$$"
rm -rf "$state"; mkdir -p "$state"
: > "$(pending_for $SID)"
out=$(run_hook "$gate" "$(pretool_payload "")")
printf '%s' "$out" | python3 -c "import json,sys; json.loads(sys.stdin.read())"
check "output stays valid JSON when the state path holds a control character" $? \
  "got: $out"

echo "pm-check-reset.sh"

for src in startup clear; do
  fresh "r1$src"
  : > "$(pending_for $SID)"
  run_hook "$reset" "$(sessionstart_payload "$src")" >/dev/null
  [ ! -f "$(pending_for $SID)" ]
  check "source=$src clears the marks" $?
done

for src in resume fork compact; do
  fresh "r2$src"
  : > "$(pending_for $SID)"
  run_hook "$reset" "$(sessionstart_payload "$src")" >/dev/null
  [ -f "$(pending_for $SID)" ]
  check "source=$src keeps the marks (gate survives)" $?
done

for src in startup compact resume; do
  fresh "r3$src"
  envfile="$work/envfile.$src"
  : > "$envfile"
  CLAUDE_ENV_FILE="$envfile" run_hook "$reset" "$(sessionstart_payload "$src")" >/dev/null
  grep -q "^export CLAUDE_PM_CHECK_DONE='$(done_for $SID)'$" "$envfile"
  check "source=$src exports CLAUDE_PM_CHECK_DONE" $? "got: $(cat "$envfile")"
done

fresh r4
run_hook "$reset" "$(sessionstart_payload startup)" >/dev/null
check "a missing CLAUDE_ENV_FILE is not an error" $?

# SessionStart re-fires on every compaction, so an unconditional >> grows the
# env file by one duplicate export per compaction for the life of the session.
fresh r5
envfile="$work/envfile.dup"
: > "$envfile"
for _ in 1 2 3 4 5; do
  CLAUDE_ENV_FILE="$envfile" run_hook "$reset" "$(sessionstart_payload compact)" >/dev/null
done
n=$(grep -c "CLAUDE_PM_CHECK_DONE" "$envfile")
[ "$n" -eq 1 ]
check "five compactions leave exactly one export line" $? "got $n lines"

echo "end to end"

# The full loop an operator sees: prompt arms it, Write is denied, the skill runs
# the exported command, the next Write goes through.
fresh e1
envfile="$work/envfile.e2e"
: > "$envfile"
CLAUDE_ENV_FILE="$envfile" run_hook "$reset" "$(sessionstart_payload startup)" >/dev/null
run_hook "$detect" "$(prompt_payload "build a slack bot for daily recaps")" >/dev/null
out=$(run_hook "$gate" "$(pretool_payload "")")
case "$out" in *'"deny"'*) r=0 ;; *) r=1 ;; esac
check "e2e: Write denied after a build-shaped prompt" $r

# Exactly what skills/pm-check/SKILL.md step 6 tells the agent to run. The
# script is invoked here, not a copy of its logic — a reimplementation in the
# test is how the earlier rounds certified behaviour nothing shipped.
( . "$envfile" && TMPDIR="$state" CLAUDE_CODE_SESSION_ID=ignored sh "$done_script" \
  >/dev/null )
check "e2e: the SKILL.md command resolves and runs" $?
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -z "$out" ]
check "e2e: Write allowed after the skill records completion" $?

# The fallback branch: no SessionStart hook ran (hooks installed mid-session), so
# the path is built from CLAUDE_CODE_SESSION_ID instead. Verified above against a
# live Claude Code run that this variable equals the hook's session_id.
fresh e2
run_hook "$detect" "$(prompt_payload "build a slack bot for daily recaps")" >/dev/null
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -n "$out" ]
check "e2e fallback: Write denied with no env file" $?
( unset CLAUDE_PM_CHECK_DONE
  TMPDIR="$state" CLAUDE_CODE_SESSION_ID="$SID" sh "$done_script" >/dev/null )
check "e2e fallback: the SKILL.md command works off CLAUDE_CODE_SESSION_ID" $?
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -z "$out" ]
check "e2e fallback: Write allowed after the fallback record" $?

echo "pm-check-done.sh"

# The failure this script exists for. CLAUDE_CODE_SESSION_ID is documented to
# report the INITIAL startup id on `--continue`/`--resume` without an explicit
# id, while the gate keys off the session id in its own payload. A bare `touch`
# writes a path nothing reads and reports success, stranding the session with no
# recovery but the opt-out. Recording must fail loudly instead.
fresh d1
: > "$(pending_for $SID)"
out=$( unset CLAUDE_PM_CHECK_DONE
       TMPDIR="$state" CLAUDE_CODE_SESSION_ID=startup-id sh "$done_script" 2>&1 )
r=$?
[ "$r" -ne 0 ]
check "a fallback id that misses the armed gate exits non-zero" $? "got rc=$r"
case "$out" in *"$(pending_for $SID)"*) r=0 ;; *) r=1 ;; esac
check "the failure names the .pending the gate is armed on" $r "got: $out"
out=$(run_hook "$gate" "$(pretool_payload "")")
case "$out" in *'"deny"'*) r=0 ;; *) r=1 ;; esac
check "the gate is still armed after a missed record" $r

# The recovery: the exact path, which both the detector's injected context and
# the deny message carry literally.
out=$( unset CLAUDE_PM_CHECK_DONE
       TMPDIR="$state" sh "$done_script" "$(done_for $SID)" 2>&1 )
check "an explicit .done path records" $? "got: $out"
out=$(run_hook "$gate" "$(pretool_payload "")")
[ -z "$out" ]
check "the explicit path lifts the gate" $?

# The cross-check is scoped to the fallback branch on purpose. CLAUDE_PM_CHECK_DONE
# is built by the reset hook from the session id it was handed, so it cannot be
# wrong — and a session that ran the check proactively has no .pending of its
# own. Crying wolf there would train the agent to ignore the output.
fresh d2
: > "$(pending_for other-session)"
out=$( TMPDIR="$state" CLAUDE_PM_CHECK_DONE="$(done_for $SID)" sh "$done_script" 2>&1 )
check "the exported path never cross-checks against another session's gate" $? \
  "got: $out"
[ -f "$(done_for $SID)" ]
check "the exported path is still recorded" $?

# Same fallback branch, nothing armed anywhere: an ungated session recording a
# proactive check is not a failure.
fresh d3
out=$( unset CLAUDE_PM_CHECK_DONE
       TMPDIR="$state" CLAUDE_CODE_SESSION_ID="$SID" sh "$done_script" 2>&1 )
check "the fallback with no gate armed is not an error" $? "got: $out"

fresh d4
out=$( unset CLAUDE_PM_CHECK_DONE
       unset CLAUDE_CODE_SESSION_ID
       TMPDIR="$state" sh "$done_script" 2>&1 )
r=$?
[ "$r" -ne 0 ]
check "neither variable set is reported, not guessed at" $? "got rc=$r: $out"

echo "install.sh settings pass"

py="$work/configure.py"
awk '/python3 - <<.PY./{f=1;next} /^PY$/{f=0} f' "$repo/install.sh" > "$py"
[ -s "$py" ]
check "the settings.json pass was extracted from install.sh" $? "extraction produced nothing"

run_configure() { # settings-json-or-empty  → prints resulting settings.json
  cfg="$work/cfg.$1"
  rm -rf "$cfg"
  mkdir -p "$cfg/hooks"
  shift
  [ -z "${1:-}" ] || printf '%s' "$1" > "$cfg/settings.json"
  CLAUDE_DIR="$cfg" python3 "$py" >"$work/configure.out" 2>&1
}

run_configure fresh ""
python3 - "$work/cfg.fresh/settings.json" <<'CHECK'
import json, sys
d = json.load(open(sys.argv[1]))
pre = d["hooks"]["PreToolUse"]
assert any("NotebookEdit" in e.get("matcher", "") for e in pre), pre
assert d["permissions"]["defaultMode"] == "auto"
assert any(h["hooks"][0]["command"].endswith("pm-check-detect.sh")
           for h in d["hooks"]["UserPromptSubmit"])
assert all("matcher" not in e for e in d["hooks"]["UserPromptSubmit"])
# The reset hook exempts forked sessions by name, so it has to be registered for
# a source it can actually receive.
reset = [e for e in d["hooks"]["SessionStart"]
         if e["hooks"][0]["command"].endswith("pm-check-reset.sh")]
assert len(reset) == 1, reset
assert "fork" in reset[0]["matcher"], reset[0]["matcher"]
CHECK
check "fresh install registers all three hooks, matcher covers NotebookEdit" $? \
  "$(cat "$work/configure.out")"

# Re-running the installer is the documented way to pick up a setup-dependent
# feature, so a second pass must be a no-op rather than a second registration.
before=$(cat "$work/cfg.fresh/settings.json")
CLAUDE_DIR="$work/cfg.fresh" python3 "$py" >"$work/configure.out" 2>&1
[ "$before" = "$(cat "$work/cfg.fresh/settings.json")" ]
check "a second installer pass changes nothing" $? "$(cat "$work/configure.out")"

# A malformed value under one event must not veto the other mutations.
run_configure badevent '{"hooks":{"PreToolUse":{"oops":true}}}'
python3 - "$work/cfg.badevent/settings.json" <<'CHECK'
import json, sys
d = json.load(open(sys.argv[1]))
assert d["hooks"]["PreToolUse"] == {"oops": True}, "the odd value was overwritten"
assert d["permissions"]["defaultMode"] == "auto", "auto mode was skipped"
assert any(h["hooks"][0]["command"].endswith("adhd-always-on.sh")
           for h in d["hooks"]["SessionStart"]), "ADHD hook was skipped"
CHECK
check "a malformed hooks.PreToolUse degrades only that event" $? \
  "$(cat "$work/configure.out")"
grep -q "WARNING" "$work/configure.out"
check "a malformed event warns the operator" $?

# Prune must only delete a registration whose script is provably gone.
prune_fixture() { # name, how-to-make-the-script
  cfg="$work/cfg.$1"
  rm -rf "$cfg"
  mkdir -p "$cfg/hooks"
  eval "$2"
  printf '{"hooks":{"UserPromptSubmit":[{"hooks":[{"type":"command","command":"%s/hooks/my-standup.sh --quiet"}]}]}}' \
    "$cfg" > "$cfg/settings.json"
  CLAUDE_DIR="$cfg" python3 "$py" >"$work/configure.out" 2>&1
  # grep -c exits 1 on zero matches, so take the count from stdout either way.
  count=$(grep -c "my-standup.sh" "$cfg/settings.json" 2>/dev/null) || count=0
  printf '%s' "${count:-0}"
}

n=$(prune_fixture symlink 'ln -s /nonexistent/dotfiles/my-standup.sh "$cfg/hooks/my-standup.sh"')
[ "$n" -ge 1 ]
check "prune KEEPS an operator hook symlinked at an unresolvable target" $? "count=$n"

n=$(prune_fixture real ': > "$cfg/hooks/my-standup.sh"')
[ "$n" -ge 1 ]
check "prune keeps an operator hook that is a real file" $? "count=$n"

n=$(prune_fixture gone 'true')
[ "$n" -eq 0 ]
check "prune drops a registration whose script is genuinely absent" $? "count=$n"

grep -q "Removing: hook for a retired bundle script" "$work/configure.out"
check "a pruned registration is named in the output" $? "$(cat "$work/configure.out")"

# settings.json symlinked into a dotfiles checkout — stow/chezmoi/by hand. The
# write must follow the link, not replace it: replacing it orphans the operator's
# real file silently, and puts the .bak in the wrong directory too.
sym="$work/symlink"
rm -rf "$sym"
mkdir -p "$sym/dotfiles" "$sym/claude/hooks"
printf '{"env":{"KEEP":"me"}}' > "$sym/dotfiles/settings.json"
ln -s "$sym/dotfiles/settings.json" "$sym/claude/settings.json"
CLAUDE_DIR="$sym/claude" python3 "$py" >"$work/configure.out" 2>&1
[ -L "$sym/claude/settings.json" ]
check "a symlinked settings.json is still a symlink after the write" $? \
  "$(cat "$work/configure.out")"
python3 - "$sym/dotfiles/settings.json" <<'CHECK'
import json, sys
d = json.load(open(sys.argv[1]))
assert d["env"]["KEEP"] == "me", "the operator's own keys were dropped"
assert "hooks" in d, "the dotfiles file never received the registrations"
CHECK
check "the write lands in the dotfiles file, preserving its contents" $? \
  "$(cat "$work/configure.out")"
[ -f "$sym/dotfiles/settings.json.bak" ]
check "the .bak lands next to the real file, not next to the symlink" $?

# Substring matching used to see these as "already registered" and skip the real
# registration forever, while still printing success.
decoy="$work/decoy"
rm -rf "$decoy"
mkdir -p "$decoy/hooks/other"
: > "$decoy/hooks/other/my-pm-check-gate.sh"
printf '{"hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"%s/hooks/other/my-pm-check-gate.sh"}]}],"UserPromptSubmit":[{"hooks":[{"type":"command","command":"logger --tag pm-check-detect.sh"}]}]}}' \
  "$decoy" > "$decoy/settings.json"
CLAUDE_DIR="$decoy" python3 "$py" >"$work/configure.out" 2>&1
python3 - "$decoy/settings.json" "$decoy" <<'CHECK'
import json, sys
d, root = json.load(open(sys.argv[1])), sys.argv[2]
def commands(event):
    return [h.get("command", "") for e in d["hooks"][event] for h in e["hooks"]]
assert f"{root}/hooks/pm-check-gate.sh" in commands("PreToolUse"), commands("PreToolUse")
assert f"{root}/hooks/pm-check-detect.sh" in commands("UserPromptSubmit"), \
    commands("UserPromptSubmit")
assert f"{root}/hooks/other/my-pm-check-gate.sh" in commands("PreToolUse"), "decoy dropped"
assert "logger --tag pm-check-detect.sh" in commands("UserPromptSubmit"), "decoy dropped"
CHECK
check "look-alike commands do not suppress the real registration" $? \
  "$(cat "$work/configure.out")"
grep -q "detect, gate, reset" "$work/configure.out"
check "the installer names which PM hooks it registered" $? "$(cat "$work/configure.out")"

echo
echo "fail-open under an unset HOME"

# Under `set -u` an unset HOME is fatal, and dash exits 2 — which Claude Code
# reads as "erase the prompt" (UserPromptSubmit) or "block the tool call"
# (PreToolUse). That inverts the fail-open contract into a silent fail-closed
# for anyone on Ubuntu running under systemd, a container, or `env -i`.
# Exit 0 is the whole assertion; these must never regress to 1 or 2 either.
for shell in dash sh bash; do
  command -v "$shell" >/dev/null 2>&1 || continue
  for hook in "$detect" "$gate"; do
    fresh "nohome-$shell-$(basename "$hook" .sh)"
    env -u HOME -u CLAUDE_CONFIG_DIR TMPDIR="$state" \
      "$shell" "$hook" </dev/null >/dev/null 2>&1
    rc=$?
    check "$shell: $(basename "$hook") exits 0 with HOME unset" "$rc" "exit was $rc"
  done
done

echo
echo "the sweep must not evict the running session"

# SessionStart re-fires on auto-compaction, so a build session still alive after
# 48h had its own .pending swept the moment it compacted — silently lifting the
# gate in exactly the case the `compact` exemption exists to protect.
fresh sweep1
: > "$(pending_for "$SID")"
touch -t 202601010000 "$(pending_for "$SID")"
: > "$state/claude-pm-check-someone-else.pending"
touch -t 202601010000 "$state/claude-pm-check-someone-else.pending"
run_hook "$reset" "$(sessionstart_payload compact)" >/dev/null
[ -f "$(pending_for "$SID")" ]
check "compact keeps this session's mark even when it is 48h+ old" $?
[ ! -f "$state/claude-pm-check-someone-else.pending" ]
check "the sweep still evicts other sessions' stale marks" $?

echo
printf '%s passed, %s failed\n' "$passed" "$failed"
[ "$failed" -eq 0 ]
